sudo: required
services:
  - docker
before_install:
  - docker build -t veeraarad/react-test -f ./client/Dockerfile ./client
scripts:
  - docker run -e CI=true veeraarad/multi-client npm run test
after_success:
  - docker build -t veeraarad/multi-client ./client
  - docker build -t veeraarad/multi-server ./server
  - docker build -t veeraarad/multi-worker ./worker
  - docker build -t veeraarad/multi-nginx ./nginx
