version: '3'
services:
  nginx:
    image: "veeraarad/multi-nginx"
    mem_limit: 128m
    restart: always
    hostname: nginx
    ports:
      - '80:80'
  server:
    image: "veeraarad/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
      - PGDATABASE=$PGDATABASE
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
  client:
    image: "veeraarad/multi-client"
    mem_limit: 128m
    hostname: client
  worker:
    image: "veeraarad/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT